### ISSUE TITLE
Not detecting incoming shielded transactions

### ISSUE THREAD

**Issue by garethtdavies** [guardawallet/zcash-community-test#1]
I have sent shielded transactions to the Sapling address generated.

1 - Via https://faucet.zcash.garethtdavies.com (Sapling->Sapling)
2 - Via ZecWallet (Sapling->Sapling)
3 - Via the taddr to Sapling address within Guarda (t->Sapling)
4 - Via ZecWallet (Transparent->Sapling) see this tx https://explorer.testnet.z.cash/tx/290f18cda73911710ce349e12f1c7db0fb6103e77b8bef4d97afeffb84fae478

None of them have appeared in the wallet and the z-addresses balance shows 0.

![Screenshot_20190611-070922](https://user-images.githubusercontent.com/135382/59279014-06a39b80-8c18-11e9-80aa-a1cce70fc24e.png)

I was able to send to a taddr.

**Comment by garethtdavies** [comment]
It appears that 3) did work after some time, perhaps after a block was mined.

**Comment by garethtdavies** [comment]
Note that the UI here is confusing as this `-0 ZEC` is actually presumably confirming the amount that was sent.

**Comment by guardawallet** [comment]
Hey! Thank you for your detailed feedback – we have looked into it and worked on solving the issue. Now, the updated version (release candidate) has been rolled out with the fixes. Ready for your tests!

**Comment by garethtdavies** [comment]
Thanks, tested this and have received shielded funds by both the faucet directly and also via a ZecWallet tx 👍
