### ISSUE TITLE
Sending from Guarda z-addr not received by external wallet

### ISSUE THREAD

**Issue by garethtdavies** [guardawallet/zcash-community-test#3]
This TX created as a fully shielded transaction in Guarda https://explorer.testnet.z.cash/tx/01ca116f178180234a8a7b5828a16118486b1c36705fc0a5f74ca244f76a45cb is not received by the external wallet (zcashd)

**Comment by str4d** [comment]
There are test vectors for Sapling note encryption available here: https://github.com/zcash/librustzcash/blob/master/zcash_primitives/src/test_vectors/note_encryption.rs

**Comment by guardawallet** [comment]
Thank you for the feedback! Fixed in the current version (ready for the test)
