### ISSUE TITLE
Sending from zaddr shows cutoff zaddr so hard to validate

### ISSUE THREAD

**Issue by garethtdavies** [guardawallet/zcash-community-test#4]
Edited to update the address is actually cutoff and not modified:

I noticed that the address is cut off during the sending confirmation. I scanned this address via QR code but on the confirmation screen it does not show the full address.

![Screenshot_20190611-130837](https://user-images.githubusercontent.com/135382/59303091-54d19280-8c4a-11e9-848d-ba36146ef2f7.png)

![Screenshot_20190611-130846](https://user-images.githubusercontent.com/135382/59303063-46837680-8c4a-11e9-96f7-4abe4860ed39.png)

**Comment by guardawallet** [comment]
Thanks a lot! Your feedback is indeed very valuable for us.
Looked into it, fixed it – the release candidate app is ready for the test!

**Comment by garethtdavies** [comment]
Thanks, I have the latest update but the issue still seems to persist.

**Comment by guardawallet** [comment]
Fixed. Check version 1.3 or above.
