### ISSUE TITLE
"Sending error" when sending from t to z addr

### ISSUE THREAD

**Issue by sigmarelax** [guardawallet/zcash-community-test#5]
I have successfully received zec to my t addr from the faucet (with 120 confirmations), but could not transfer from my guarda t addr to the guarda generated ztestsapling* address. Have tried multiple transfer amounts and transaction fees, each time it returns "sending error." Sending from that t address to the donation t address for the test net faucet was successful. 

Using guarda shielded version .43 on an Android 9.0 device

a logcat from adb (taken as the sending fails) returns:
```
06-14 12:18:27.607 25276 25276 D psd     : clearText body 1 16: bad-txns-sapling-output-description-invalid. Code:-26
06-14 12:18:27.641 25276 25276 D psd     : CurrencyUtils.getBtcLikeError() - com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $
06-14 12:18:27.650 25276 25276 D SendingCurrencyActivity: broadcastRawTxZexNew e=16: bad-txns-sapling-output-description-invalid. Code:-26
```
[Here is a more of the logs](https://gist.github.com/sigmarelax/0e3ab52be2e11768ee391bf7a002d802)

Please let me know if this is user error or if I can provide more information

**Comment by garethtdavies** [comment]
I can replicate this sending from t->z

```
06-14 12:56:30.495 D/svcom   (12102): clearText body 16: bad-txns-sapling-output-description-invalid. Code:-26
06-14 12:56:30.495 D/psd     (12102): clearText body 1 16: bad-txns-sapling-output-description-invalid. Code:-26
06-14 12:56:30.533 D/psd     (12102): CurrencyUtils.getBtcLikeError() - com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $
06-14 12:56:30.546 D/SendingCurrencyActivity(12102): broadcastRawTxZexNew e=16: bad-txns-sapling-output-description-invalid. Code:-26
```

Note that it also occurred on a z->z tx

**Comment by guardawallet** [comment]
Thank you for your feedback!
Already fixed. Check version 1.3 or above.
