### ISSUE TITLE
Sending error z->z

### ISSUE THREAD

**Issue by garethtdavies** [guardawallet/zcash-community-test#7]
After the 1.15 update I am able to sync the wallet. Once synced I have tried to send a z->z transaction but it always fails either with `bad-txns-joinsplit-requirements-not-met. Code:-26` or `err=src.length=2 srcPos=0 dst.length=192 dstPos=0 length=192`. These are relevant sections from adb debugging:

```
06-30 20:22:27.671 D/svcom   ( 7621): clearText body 18: bad-txns-joinsplit-requirements-not-met. Code:-26
06-30 20:22:27.672 D/psd     ( 7621): clearText body 1 18: bad-txns-joinsplit-requirements-not-met. Code:-26
06-30 20:22:27.702 D/CurrencyUtils( 7621): getBtcLikeError() - com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $
06-30 20:22:27.712 D/SendingCurrencyActivity( 7621): broadcastRawTxZexNew e=18: bad-txns-joinsplit-requirements-not-met. Code:-26
```
```
06-30 20:20:22.234 D/SendingCurrencyActivity( 7621): z to z - onResponse src.length=2 srcPos=0 dst.length=192 dstPos=0 length=192
06-30 20:20:22.255 D/SendingCurrencyActivity( 7621): z to z - err=src.length=2 srcPos=0 dst.length=192 dstPos=0 length=192
```

The screenshot shows I have a synced wallet:

![Screenshot_20190630-202706](https://user-images.githubusercontent.com/135382/60408941-f414e600-9b75-11e9-80b0-9337f0c6852d.png)

**Comment by guardawallet** [comment]
Looks like your wallet was syncing while we had an issue last week. You need to save your private key (WIF), log out and restore with the key. After that, the wallet will sync from the start (it takes a few minutes).

If it doesn't work you need to save a private key, clear app data (Settings -> Apps -> Guarda Shielded -> Storage -> Clear data) and restore with the private key.

**Comment by garethtdavies** [comment]
Same issue and reproduced a couple of ways. I cleared the data, restored the wallet and again `bad-txns-joinsplit-requirements-not-met`. I then uninstalled the app, reinstalled, created a new wallet and send a new transaction to it. I then tried sending and got the `bad-txns-joinsplit-requirements-not-met` again.

**Comment by guardawallet** [comment]
We've fixed another backend issue. So you need to uninstall (or clear data) just one more time.

**Comment by garethtdavies** [comment]
It worked 😄 💥 🎉 

I can make this a separate issue but when the app is first loaded there is no syncing message displayed though I guess it is doing stuff in the background as eventually after a few minutes, the restored funds show up. It's a bit confusing as it appears that nothing is happening. It only showed me the syncing message when I scanned an address to send.

**Comment by woodlarktomorrow** [comment]
I just installed Shielded Guarda (v. 1.20) and am having the same issue. I can receive ZEC at my t-address and I can send ZEC from my t-address to my z-address, but when attempting to transfer from my z-address to another z-address I get this error: err=src.length=2 srcPos=0 dst.length=192 dstPos=0 length=192.

I have tried logging out and clearing all app storage and then restoring the wallet using the private key. After waiting for syncing to finish I still get the same error.

**Comment by guardawallet** [comment]
Hi!

Thank you for your feedback.

There was an issue on the server side.
Please update your app to version 1.21 (maybe resync or clear data will be required).

@woodlarktomorrow Send please your device name and Android version if you'll still have the issue.
