### ISSUE TITLE
Syncing error

### ISSUE THREAD

**Issue by garethtdavies** [guardawallet/zcash-community-test#8]
![Screenshot_20190704-175149](https://user-images.githubusercontent.com/135382/60691513-0bf5ae00-9e85-11e9-8e63-4fae39486770.png)

I am stuck with one of my transactions forever "Syncing" despite the wallet being synced. Clicking on this syncing transaction shows it has 0 confirmations whereas it now has over 100. This transaction was sent from the wallet and received at the other end but never updated locally.

**Comment by guardawallet** [comment]
Hi!

Thank you for your feedback.
There was an issue on the server side.
Please update your app to version 1.21 (maybe resync or clear data will be required).
