### ISSUE TITLE
"TxOutRoom.a() on null object reference" error on z->z

### ISSUE THREAD

**Issue by tromer** [guardawallet/zcash-community-test#9]
I funded my Guarda Shielded 1.15 wallet via a z->z transfer (the balance appeared), and then tried to do a z->z transfer from the wallet to its own z-addr. I get this error (shown in a popup at the bottom of the sending screen)
> Sending error: Attempt to invoke virtual method 'java.lang.String com.guarda.zcash.sapling.db.model.TxOutRoom.a()' on a null object reference

**Comment by guardawallet** [comment]
Hi!

Thank you for your feedback.
There was an issue on the server side.
Please update your app to version 1.21 (maybe resync or clear data will be required).
